# Generated by Django 3.2 on 2021-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0002_alter_content_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='set_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
