# Generated by Django 3.2 on 2021-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0003_auto_20210526_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='set_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
