# Generated by Django 3.2 on 2021-05-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0004_auto_20210526_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workoutapp.event'),
        ),
    ]
