# Generated by Django 3.2 on 2021-05-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0005_alter_content_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
