# Generated by Django 3.2.4 on 2021-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0006_alter_content_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
