# Generated by Django 3.2.4 on 2021-06-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutapp', '0007_content_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
